// examples/stencil/src/components/popover.tsx
import { Component, Element, h } from "@stencil/core";

@Component({
  tag: "rt-stencil-popover",
  shadow: true,
  styleUrl: "../../../shared/components.css",
})
export class StencilPopover {
  @Element() host!: HTMLElement;

  componentDidLoad() {
    const root = this.host.shadowRoot as ShadowRoot & { referenceTarget: string };
    root.referenceTarget = "panel";
    this.host.setAttribute("data-renderer-ready", "");
    this.host.dispatchEvent(new CustomEvent("renderer-ready"));
  }

  render() {
    return (
      <div id="panel" popover="auto" role="dialog" aria-labelledby="panel-title">
        <p class="eyebrow">Stencil component</p>
        <h2 id="panel-title">Rendered with Stencil</h2>
        <p>This native popover lives inside a Stencil component’s shadow root.</p>
        <button type="button" popoverTarget="panel" popoverTargetAction="hide" autoFocus>Close popover</button>
      </div>
    );
  }
}

// examples/svelte/popover.svelte
<svelte:options customElement={{
  shadow: "open",
  extend: Base => class extends Base {
    constructor() {
      super();
      this.shadowRoot.referenceTarget = "panel";
    }
  },
}} />

<script>
  import { onMount } from "svelte";
  import componentStyles from "../shared/components.css";

  onMount(() => {
    const host = $host();
    host.setAttribute("data-renderer-ready", "");
    host.dispatchEvent(new Event("renderer-ready"));
    return () => host.removeAttribute("data-renderer-ready");
  });
</script>

<svelte:element this={"style"}>{componentStyles}</svelte:element>
<div id="panel" popover="auto" role="dialog" aria-labelledby="panel-title">
  <p class="eyebrow">Svelte custom element · shadow DOM</p>
  <h2 id="panel-title">Rendered with Svelte</h2>
  <p>This native popover lives inside a compiler-generated Svelte custom element.</p>
  <button type="button" popovertarget="panel" popovertargetaction="hide">Close popover</button>
</div>
