// examples/svelte/checkbox.svelte
<svelte:options customElement={{
  shadow: "open",
  props: { revision: { type: "Number", reflect: true } },
  extend: Base => class extends Base {
    constructor() {
      super();
      this.shadowRoot.referenceTarget = "control";
    }
  },
}} />

<script>
  import { onMount } from "svelte";
  import componentStyles from "../shared/components.css";

  let { revision = 0 } = $props();

  onMount(() => {
    const host = $host();
    host.setAttribute("data-renderer-ready", "");
    host.dispatchEvent(new Event("renderer-ready"));
    return () => host.removeAttribute("data-renderer-ready");
  });
</script>

<svelte:element this={"style"}>{componentStyles}</svelte:element>
<div class="component-preview">
  {#key revision}
    <input id="control" type="checkbox" data-revision={revision}>
  {/key}
  <span aria-hidden="true">Native checkbox</span>
</div>
<p class="hint">Render revision {revision}</p>

// examples/stencil/src/components/checkbox.tsx
import { Component, Element, Fragment, h, Prop } from "@stencil/core";

@Component({
  tag: "rt-stencil-checkbox",
  shadow: true,
  styleUrl: "../../../shared/components.css",
})
export class StencilCheckbox {
  @Element() host!: HTMLElement;
  @Prop() revision: number = 0;

  componentDidLoad() {
    const root = this.host.shadowRoot as ShadowRoot & { referenceTarget: string };
    root.referenceTarget = "control";
    this.host.setAttribute("data-renderer-ready", "");
    this.host.dispatchEvent(new CustomEvent("renderer-ready"));
  }

  render() {
    return (
      <Fragment>
        <div class="component-preview">
          <input key={this.revision} id="control" type="checkbox" data-revision={this.revision} />
          <span aria-hidden="true">Native checkbox</span>
        </div>
        <p class="hint">Render revision {this.revision}</p>
      </Fragment>
    );
  }
}
